export const KanbanContextActions = {
  ON_DRAG_END: "ON_DRAG_END",
  ADD_COLUMN_ITEM: "ADD_CoLUMN_ITEM",
  ADD_COLUMN: "ADD_COLUMN",
  EDIT_COLUMN_TITLE: "EDIT_COLUMN_TITLE",
  EDIT_CARD_TITLE: "EDIT_CARD_TITLE",
  EDIT_CARD_DESCRIPTION: "EDIT_CARD_DESCRIPTION",
  DELETE_COLUMN: "DELETE_COLUMN",
  DELETE_CARD: "DELETE_CARD",
};
